version: 1
builder:
  configs:
  - platform: ios
    target: FlowNavigation
  - platform: macos-xcodebuild
    target: FlowNavigation
  - platform: tvos
    target: FlowNavigation
  - platform: watchos
    target: FlowNavigation
  - documentation_targets: [FlowNavigation]