name: Swift CI

on:
  pull_request:  # Runs when pushing to a pull request
    branches: [main]
  push:  # Runs when merging to main
    branches: [main]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Pulls your repo into the CI environment

      - name: Set Up Latest Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"

      - name: Get Swift Version
        run: swift --version  # Should print Swift 6.0.2

      - name: Build the Project
        run: swift build

      - name: Run Tests
        run: swift test -Xswiftc -strict-concurrency=complete --enable-code-coverage
