name: Swift 5.7 CI

on:
  pull_request:  # Runs when pushing to a pull request
    branches: [main]
  push:  # Runs when merging to main
    branches: [main]

jobs:
  run-tests:
    runs-on: macos-13

    steps:
      - name: Select Xcode 14.1
        run: sudo xcode-select -s "/Applications/Xcode_14.1.app/Contents/Developer"

      - name: Checkout Repository
        uses: actions/checkout@v4 # Pulls your repo into the CI environment

      - name: Get Swift Version
        run: swift --version  # Should print Swift ~= 5.7

      - name: Get Swift Tools Version
        run: swift package tools-version  # Should print Swift ~= 5.7

      - name: Run Tests - Swift 5.7
        run: swift test
