name: Update README package version

on:
  pull_request:  # Runs when pushing to a pull request that targets main
    branches: [main]

permissions:
  contents: write
  
jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important: fetch all history and tags
      
      - name: Get latest tag
        id: get_version
        run: |
          TAG=$(git describe --tags --abbrev=0)
          VERSION=${TAG#v}  # strip 'v' prefix
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      
      - name: Update README.md with new version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          echo "Using version: $VERSION"
          sed -i -E "s|(.package\(url: \"https://github.com/magnuskahr/swiftui-flow-navigation\", from: \")[^\"]+(\"\))|\1$VERSION\2|" README.md
      
          if git diff --quiet README.md; then
            echo "README already up to date."
          else
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add README.md
            git commit -m "Update README to version $VERSION"
            git push
          fi
