name: Update README package version

on:
  pull_request:  # Runs when pushing to a pull request
    branches: [main]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: |
          RAW_TAG=${{ github.event.release.tag_name }}
          CLEAN_TAG=${RAW_TAG#v}  # strip leading 'v' if present
          echo "version=$CLEAN_TAG" >> $GITHUB_OUTPUT

      - name: Update README.md with new version
        run: |
          VERSION=${{ steps.get_version.outputs.version }}
          sed -i 's|\(.package(url: "https://github.com/magnuskahr/swiftui-flow-navigation", from: "\)[^"]\+\("\))|\1'"$VERSION"'\2|' README.md
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README to version $VERSION"
          git push
